#!/bin/bash 

# add repo
rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

cat << EOF > /etc/yum.repos.d/elastic.repo
[elasticsearch-2.x]
name=Elasticsearch repository for 2.x packages
baseurl=https://packages.elastic.co/elasticsearch/2.x/centos
gpgcheck=1
gpgkey=https://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1
EOF

# install ES
yum install elasticsearch -y

# turn on for ES for default runlevel
chkconfig --add elasticsearch

# let ES listen on localhost only
sed -i.bak 's|# network.host: 192.168.0.1| network.host: localhost|g' /etc/elasticsearch/elasticsearch.yml

# start ES
/etc/init.d/elasticsearch start
