#!/bin/bash

# add repo
cat <<EOF > /etc/yum.repos.d/mongodb-org-3.2.repo
[mongodb-org-3.2]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.2/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-3.2.asc
EOF

# install mongo
yum install -y mongodb-org

# turn on mongod for default runlevel
chkconfig mongod on

# start mongo
service mongod start
