#!/bin/bash
# Install WordPress
# Sam Hagin

# Color constants
ansi_black='\033[30m'
ansi_black_bold='\033[0;30;1m'
ansi_red='\033[31m'
ansi_red_bold='\033[0;31;1m'
ansi_green='\033[32m'
ansi_green_bold='\033[0;32;1m'
ansi_yellow='\033[33m'
ansi_yellow_bold='\033[0;33;1m'
ansi_blue='\033[34m'
ansi_blue_bold='\033[0;34;1m'
ansi_magenta='\033[35m'
ansi_magenta_bold='\033[0;35;1m'
ansi_cyan='\033[36m'
ansi_cyan_bold='\033[0;36;1m'
ansi_white='\033[37m'
ansi_white_bold='\033[0;37;1m'
ansi_reset='\033[0m'

salt=$( curl -s https://api.wordpress.org/secret-key/1.1/salt/)

usage() { echo "Usage: $0 [ -b <database name> ] [-d <full path to directory>] [-p <password for database user>] [-u username]" 1>&2; exit 1; }

while getopts ":d:p:u:b:" o; do
    case "${o}" in
        b)
	    b=${OPTARG}
	    ;;
        d)
            d=${OPTARG}
            if [[ ! -d $d ]]; then
	    echo -e $ansi_red "Directory does not exists" $ansi_reset
	    echo -e $ansi_green "Creating directory...." $ansi_reset
	    mkdir -pv $d

	fi
            ;;
        p)
            p=${OPTARG}
            ;;
	u)
	    u=${OPTARG}
	    ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [[ -z "${d}" ]] || [[ -z "${b}" ]] || [[ -z "{$p}" ]] || [[ -z "{$u}" ]]; then
    usage
    exit
fi

echo -e $ansi_green "Downloading WordPress" $ansi_reset
cd $d || exit

# check for existing WP install
[[ -f wp-config.php ]] && echo -e $ansi_red "It appears another WordPress installation exists in" $ansi_reset $ansi_blue $d $ansi_reset && exit
wget http://wordpress.org/latest.tar.gz --no-check-certificate
tar -xvzf latest.tar.gz
mv -v wordpress/* .
rmdir wordpress
\rm  -v latest.tar.gz


echo -e $ansi_green "Creating database, user and assigning privileges" $ansi_reset
mysql -e "Create database $b" || echo -e $ansi_red "Database already exists" $ansi_reset
mysql -e "Grant all privileges on $b.* to '$u'@'localhost' identified by '$p'"

echo -e $ansi_green "Generating wp-config.php file" $ansi_reset

cat << EOF > wp-config.php
<?php
/**
 * The base configurations of the WordPress.
 *
 * This file has the following configurations: MySQL settings, Table Prefix,
 * Secret Keys, WordPress Language, and ABSPATH. You can find more information
 * by visiting {@link http://codex.wordpress.org/Editing_wp-config.php Editing
 * wp-config.php} Codex page. You can get the MySQL settings from your web host.
 *
 * This file is used by the wp-config.php creation script during the
 * installation. You don't have to use the web site, you can just copy this file
 * to "wp-config.php" and fill in the values.
 *
 * @package WordPress
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', '$b');

/** MySQL database username */
define('DB_USER', '$u');

/** MySQL database password */
define('DB_PASSWORD', '$p');

/** MySQL hostname */
define('DB_HOST', 'localhost');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */

$salt

/**#@-*/

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each a unique
 * prefix. Only numbers, letters, and underscores please!
 */
\$table_prefix  = 'wp_';

/**
 * WordPress Localized Language, defaults to English.
 *
 * Change this to localize WordPress. A corresponding MO file for the chosen
 * language must be installed to wp-content/languages. For example, install
 * de_DE.mo to wp-content/languages and set WPLANG to 'de_DE' to enable German
 * language support.
 */
define('WPLANG', '');

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 */
define('WP_DEBUG', false);

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
EOF

echo -e $ansi_green "Setting file ownership to www-data" $ansi_reset
chown -vR www-data. *

echo -e $ansi_green "Setup Completed" $ansi_reset
